#pragma once
#define MKSMHOOK_VERSION "0.1"
#include "core.h"
#include "pad.h"
#include "menu.h"
#include "monk.h"
#include "draw.h"
#include "minterface.h"
#include "camera.h"
#include "vector.h"
#include "string_dict.h"
#include "pxMath.h"
